name: LazyCategories
version: "2021.08-01"
license: "GPL-2.0-or-later"
date: 2021-08-30
description: |
    Construct an equivalent lazy category out of a CAP category

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "ToolsForHomalg"
      version: ">= 2020.09.06"
      url: "https://homalg-project.github.io/pkg/ToolsForHomalg"
    - name: "CAP"
      version: ">= 2020.04.15"
      url: "https://homalg-project.github.io/pkg/CAP"
    - name: "MonoidalCategories"
      version: ">= 2020.03.01"
      url: "https://homalg-project.github.io/pkg/MonoidalCategories"
    - name: "CategoryConstructor"
      version: ">= 2020.08.16"
      url: "https://homalg-project.github.io/pkg/CategoryConstructor"
    - name: "Digraphs"
      version: ">= 0.12.1"
      url: "https://digraphs.github.io/Digraphs"

www: https://homalg-project.github.io/pkg/LazyCategories
readme: README.md
packageinfo: https://homalg-project.github.io/LazyCategories/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/LazyCategories/releases/download/v2021.08-01/LazyCategories-2021.08-01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/LazyCategories/releases/download/v2021.08-01/LazyCategories-2021.08-01.zip

pdf: https://github.com/homalg-project/LazyCategories/releases/download/v2021.08-01/LazyCategories-2021.08-01.pdf

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bar21</span>]   <b class='BibAuthor'>Barakat, M.</b>,
     <i class='BibTitle'>LazyCategories, Construct an equivalent lazy category out of a CAP category,
             Version 2021.08-01</i>
     (<span class='BibYear'>2021</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/pkg/LazyCategories">https://homalg-project.github.io/pkg/LazyCategories</a></span>.
    </p>
    

bibtex: |
    @misc{ LazyCategories2021.08-01,
      author =           {Barakat, M.},
      title =            {{LazyCategories},   Construct   an   equivalent   lazy
                          category out of a CAP category, {V}ersion 2021.08-01},
      month =            {Aug},
      year =             {2021},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/pkg/LazyCategories}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{pkg/}\discretionary
                          {}{}{}\texttt{LazyCategories}}},
      printedkey =       {Bar21}
    }

