name: LazyCategories
version: "2020.10.01"
license: "GPL-2.0-or-later"
date: 2020-10-01
description: |
    Construct an equivalent lazy category out of a CAP category

authors:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

maintainers:
    - name: Mohamed Barakat
      url: https://mohamed-barakat.github.io/

GAP: ">= 4.9.1"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "ToolsForHomalg"
      version: ">= 2020.09.06"
      url: "https://homalg-project.github.io/homalg_project/ToolsForHomalg"
    - name: "CAP"
      version: ">= 2020.04.15"
      url: "https://homalg-project.github.io/CAP_project/CAP"
    - name: "MonoidalCategories"
      version: ">= 2020.03.01"
      url: "https://homalg-project.github.io/CAP_project/MonoidalCategories"
    - name: "CategoryConstructor"
      version: ">= 2020.08.16"
      url: "https://homalg-project.github.io/CategoryConstructor"
    - name: "Digraphs"
      version: ">= 0.12.1"
      url: "https://gap-packages.github.io/Digraphs"

www: https://homalg-project.github.io/LazyCategories
readme: README.md
packageinfo: https://homalg-project.github.io/LazyCategories/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/LazyCategories/releases/download/v2020.10.01/LazyCategories-2020.10.01.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bar20</span>]   <b class='BibAuthor'>Barakat, M.</b>,
     <i class='BibTitle'>LazyCategories, Construct an equivalent lazy category out of a CAP category,
             Version 2020.10.01</i>
     (<span class='BibYear'>2020</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://homalg-project.github.io/LazyCategories">https://homalg-project.github.io/LazyCategories</a></span>.
    </p>
    

bibtex: |
    @misc{ LazyCategories2020.10.01,
      author =           {Barakat, M.},
      title =            {{LazyCategories},   Construct   an   equivalent   lazy
                          category out of a CAP category, {V}ersion 2020.10.01},
      month =            {Oct},
      year =             {2020},
      note =             {GAP package},
      howpublished =     {\href
                          {https://homalg-project.github.io/LazyCategories}
                          {\texttt{https://homalg-project.github.io/}\discretionary
                          {}{}{}\texttt{LazyCategories}}},
      printedkey =       {Bar20}
    }

